[bell]
animation = "EaseOutExpo"
duration = 0

# this is a test comment

[[colors.indexed_colors]]
color = "#F5A97F"
index = 16

[[colors.indexed_colors]]
color = "#F4DBD6"
index = 17

[colors.bright]
black = "#5B6078"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#A5ADCB"
yellow = "#EED49F"

[colors.cursor]
cursor = "#F4DBD6"
text = "#24273A"

[colors.dim]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[colors.hints.end]
background = "#A5ADCB"
foreground = "#24273A"

[colors.hints.start]
background = "#EED49F"
foreground = "#24273A"

[colors.normal]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[colors.primary]
background = "#24273A"
bright_foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
foreground = "#CAD3F5"

[colors.search.focused_match]
background = "#A6DA95"
foreground = "#24273A"


[colors.search.matches]
background = "#A5ADCB"
foreground = "#24273A"

[colors.selection]
background = "#F4DBD6"
text = "#24273A"

[colors.vi_mode_cursor]
cursor = "#B7BDF8"
text = "#24273A"

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Command"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.8

[window.padding]
x = 10
y = 10

# this is an upstream test comment
